### ISSUE TITLE
Spring Boot 3.0.x에서 Gson이 자동인식되지 않는 현상

### ISSUE THREAD

**Issue by mklinkj** [mklinkj/vue-study#1]
## 문제
postman 설치하고 싶지 않아서, 그냥 spring boot로 rest api 서버 프로젝트를 만들었는데...

rest-api-server 프로젝트의 JSON 컨버터를 Gson을 사용하려고 build.gradle에 Gson을 추가해뒀는데, 자동인식이 안되고, jackson이 기본으로 처리된다.

## 해결
* application.yml (spring boot 3.0.x 기준)
  ```yml
  spring:
    mvc:
      converters:
        preferred-json-mapper: gson
  ```

아마도 jackson은 별도 라이브러리 추가를 안해도 추가가되서 그걸로 기본으로되는 것 같은데.. yml에 위와 같이 설정을 해주면 gson으로 처리할 수 있었다.

### 알게된 계기...
gson의 경우 null로 설정된 필드가 직렬화 대상에 포함되지 않는데.. 나타나길레 gson으로 처리되지 않는 것을 알게되었음.. 😅
